### ISSUE TITLE
not working with version  May 29, 2019

### ISSUE THREAD

**Issue by Jmos** [prezesp/scoop-viewer#23]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "webapp\routes.py", line 72, in get_bucket
  File "webapp\utils.py", line 33, in get_apps
  File "explorer\explorer.py", line 23, in get_apps
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'x:\\scoop\\jmos\\apps\\scoop\\current\\bucket'

**Comment by prezesp** [comment]
Try it now with a new version of scoop-viewer (v0.8)
The only thing that you need is running `scoop update scoop-viewer`

Fixed in https://github.com/prezesp/scoop-viewer/pull/24
