### ISSUE TITLE
some buckets content not displayed

### ISSUE THREAD

**Issue by Jmos** [prezesp/scoop-viewer#25]
some buckets content not displayed may be character set problem

[2019-06-20 08:47:28,139] ERROR in app: Exception on /bucket/Main-bucket/ [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "webapp\routes.py", line 78, in get_bucket
  File "webapp\utils.py", line 33, in get_apps
  File "explorer\explorer.py", line 33, in get_apps
  File "explorer\explorer.py", line 27, in browse
  File "explorer\explorer.py", line 14, in parse_json
  File "json\__init__.py", line 296, in load
  File "C:\Python36-x64\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 805: character maps to <undefined>
[2019-06-20 08:47:56,815] ERROR in app: Exception on /bucket/Ash258/ [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "webapp\routes.py", line 78, in get_bucket
  File "webapp\utils.py", line 33, in get_apps
  File "explorer\explorer.py", line 33, in get_apps
  File "explorer\explorer.py", line 27, in browse
  File "explorer\explorer.py", line 14, in parse_json
  File "json\__init__.py", line 296, in load
  File "C:\Python36-x64\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 805: character maps to <undefined>
[2019-06-20 08:49:54,276] ERROR in app: Exception on /bucket/extras/ [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "webapp\routes.py", line 78, in get_bucket
  File "webapp\utils.py", line 33, in get_apps
  File "explorer\explorer.py", line 33, in get_apps
  File "explorer\explorer.py", line 27, in browse
  File "explorer\explorer.py", line 14, in parse_json
  File "json\__init__.py", line 296, in load
  File "C:\Python36-x64\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 150: character maps to <undefined>

**Comment by brunnels** [comment]
I'm seeing the same.  The latest update fixed all of my other buckets but "extras" bucket still has that error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 150: character maps to <undefined>`

**Comment by prezesp** [comment]
Thank you for the issue.
Please run `scoop update` and `scoop update scoop-viewer` to get newest version.
